@baseUrl = http://localhost:4004

@imgNP = e35b60f0-cdd7-42a9-812d-97cf4a1008c5

### Procesar DOX ###
POST {{baseUrl}}/service/uploadPhoto/Fotos({{imgNP}})/uploadPhoto.dox
Content-Type: application/json

{
  
}

### WATCH Values 
GET {{baseUrl}}/service/facturasbackendService/Values

### WATCH Datos
GET {{baseUrl}}/service/facturasbackendService/Datos

### new updated value
POST {{baseUrl}}/service/facturasbackendService/Values
Content-Typce: application/json

{ 
  "value" : "Cinta 2.0",
  "datos_ID": "e35b60f0-cdd7-42a9-812d-24676d2b0477"
}


### Send to B1  
POST {{baseUrl}}/service/facturasbackendService/Fotos({{imgNP}})/facturasbackendService.enviar
Content-Type: application/json

{ 
  
}

###
GET {{baseUrl}}/service/facturasbackendService/Values


### GETTERS ###
### GET ALL PHOTOS
GET {{baseUrl}}/service/facturasbackendService/Fotos

### GET IMAGEN
GET {{baseUrl}}/service/facturasbackendService/Fotos({{imgNP}})/enviado/$value

### GET ALL PHOTOS
GET {{baseUrl}}/service/facturasbackendService/Datos

###
GET {{baseUrl}}/service/facturasbackendService/Fotos({{imgNP}})/datosHeader