@baseUrl = http://localhost:4004

@imgNP = e35b60f0-cdd7-42a9-812d-97cf4a1008c5

### Procesar DOX ###
POST {{baseUrl}}/service/uploadPhoto/Fotos({{imgNP}})/uploadPhoto.dox
Content-Type: application/json

{
  
}

### GET FOTO
GET {{baseUrl}}/service/facturasbackendService/Fotos({{imgNP}})

### GET DATOS ITEMS  
GET {{baseUrl}}/service/facturasbackendService/Fotos({{imgNP}})/datosItems

###
GET {{baseUrl}}/service/facturasbackendService/Datos


### GET DATOS HEADER
# @name header
GET {{baseUrl}}/service/facturasbackendService/Fotos({{imgNP}})/datosHeader

###
@dato = {{header.response.body.value[0].ID}}

### GET VALUES
# @name values
GET {{baseUrl}}/service/facturasbackendService/Datos?$expand=value

###
@value = {{values.response.body.value[0].ID}} 

### GET VALUE 
GET {{baseUrl}}/service/facturasbackendService/Values({{value}})


### AGREGAR VALUE
POST {{baseUrl}}/service/facturasbackendService/Values
Content-Type: application/json

{
    "value": "1234567",
    "datos_ID": "e35b60f0-cdd7-42a9-812d-1967dcc02d45"
}


### CHECK VALUES
GET {{baseUrl}}/service/facturasbackendService/Values?$filter=datos_ID eq e35b60f0-cdd7-42a9-812d-1967588a8b87


### ENVIAR DATOS
POST {{baseUrl}}/service/facturasbackendService/Fotos({{imgNP}})/facturasbackendService.enviar
Content-Type: application/json

{
  
}
