@baseUrl = http://localhost:4004
@datoAG = 6eaf9905-9f8a-48af-998b-908587ef7100
@imgP =  d5a5d07c-a193-4e59-98de-7d36557a35e8
@imgNP = bee70546-10d7-455d-8055-841566efa451

### GETTERS ###
### GET ALL PHOTOS
GET {{baseUrl}}/service/facturasbackendService/Fotos


### GET ALL DATA
GET {{baseUrl}}/service/facturasbackendService/DatosHeader

### GET ALL DATA
GET {{baseUrl}}/service/facturasbackendService/DatosItems


### SETTERS ###
### SEND PHOTO
# @name newPhoto
POST {{baseUrl}}/service/facturasbackendService/Fotos
Content-Type: application/json

{
    
}

###
@photoNAG = {{newPhoto.response.body.$.ID}}



### Upload Fotos
POST {{baseUrl}}/service/uploadPhoto/Fotos({{photoNAG}})/uploadPhoto.upload
Content-Type: application/json
Content-Length: -1

{
  "imagen": ""
}


### Procesar DOX ###
POST {{baseUrl}}/service/uploadPhoto/Fotos({{imgNP}})/uploadPhoto.dox
Content-Type: application/json

{
  
}