/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const add_Imagen = require('./code/add-imagen');
const check_Foto_Procesado = require('./code/check-foto-procesado');
const dOX = require('./code/dOX');
const set_Procesado = require('./code/set-procesado');

class uploadPhoto extends LCAPApplicationService {
    async init() {

        this.on('upload', 'Fotos', async (request, next) => {
            return add_Imagen(request);
        });

        this.before('dox', 'Fotos', async (request) => {
            await check_Foto_Procesado(request);
        });

        this.on('dox', 'Fotos', async (request, next) => {
            return dOX(request);
        });

        this.after('dox', 'Fotos', async (results, request) => {
            await set_Procesado(results, request);
        });

        return super.init();
    }
}


module.exports = {
    uploadPhoto
};