/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const dox_Logic = require('./code/dox-logic');
const upload_Logic = require('./code/upload-logic');
const datos_Logic = require('./code/datos-logic');
const enviar_Logic = require('./code/enviar-logic');
const update_Datos_Logic = require('./code/update-datos-logic');

class service extends LCAPApplicationService {
    async init() {

        this.on('dox', 'Fotos', async (request, next) => {
            return dox_Logic(request);
        });

        this.on('upload', 'Fotos', async (request, next) => {
            return upload_Logic(request);
        });

        this.on('datos', 'Fotos', async (request, next) => {
            return datos_Logic(request);
        });

        this.on('enviar', 'Fotos', async (request, next) => {
            return enviar_Logic(request);
        });

        this.on('update_datos', 'Fotos', async (request, next) => {
            return update_Datos_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    service
};