/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const add_Imagen = require('./code/add-imagen');
const dOX = require('./code/dOX');

class uploadPhoto extends LCAPApplicationService {
    async init() {

        this.on('upload', 'Fotos', async (request, next) => {
            return add_Imagen(request);
        });

        this.on('dox', 'Fotos', async (request, next) => {
            return dOX(request);
        });

        return super.init();
    }
}


module.exports = {
    uploadPhoto
};